### ISSUE TITLE
Heat-tolerant wifi networking gear

### ISSUE THREAD

**Issue by DavidRamage** [psas/Launch-12#22] opened 2014-07-22 00:41 UTC
Our current wifi gear works great in the cool comfort of the lab, but behaves erratically in the desert.  We need to either buy or make something which can handle being in the desert in the Summer and still work.

**Comment by DavidRamage** [comment] 2014-07-28 01:27
After talking with some other folks it is possible that heat isn't the issue.  A 60 watt blub and a clamp-on lamp can heat the interior of a cardboard box up over 90 degrees quite well.  I plan to take the router home with me on Tuesday and test it while it is hot.

**Comment by DavidRamage** [comment] 2014-08-01 02:16
I heated the router up to about 100 degrees and copied a 4 gigabyte file between two computers connected to it, twice, while running a continuous ping.  Both copies completed successfully, and the packet loss on the ping was about 1%. More tests should be done, but it looks like heat isn't the issue.

**Comment by DavidRamage** [comment] 2014-08-06 04:04
On Tuesday 8/12 we will be running active tests of all RF gear.  Kenny will bring his software defined radio gear, and we will be doing packet captures.  David is going to see if the ports on the router can be made into monitor ports so we can capture wired traffic too.

**Comment by novelistparty** [comment] 2014-08-11 19:12
There was the concern that maybe the power was too noisy.

**Comment by BartMassey** [comment] 2014-08-11 19:34
I'm also not 100% convinced that the router itself was actually the root cause of the problem. The RF environment at the launch site was a mess AFAICT.

**Comment by natronics** [comment] 2014-08-11 20:51
Indeed. We're testing this piece by piece to come up with a root cause. Next up is spectrum analysis with all the equipment running.

**Comment by DavidRamage** [comment] 2014-08-12 02:13
Our current plan is to perform a test tomorrow night.  Kenny is going to bring his SDR gear, and we'll be running packet captures of both wifi and wired networks as well.

**Comment by DavidRamage** [comment] 2014-08-14 02:17
We made the following observations during last night's test:
1 - Our HTs raise the noise floor in the 70cm band, even when they're tuned to transmit at 2 meters.
2 - When the WIFI amp is on, it emits a signal at 1.5 GHz.  This may possibly interfere with the GPS.
3 - At one point in time, powering up the WIFI amp coincided with the Trackmaster losing its connection with the rocket.

It is important to keep in mind that these tests were all performed indoors.  RF multipathing could very well have caused readings that would not be present in the field.

**Comment by andrewgreenberg** [comment] 2015-06-28 06:04
Given the testing we did last weekend, and the new networking gear, I'm closing this issue.

**Closed as completed by andrewgreenberg** 2015-06-28 06:04 UTC
Labels: Priority: Critical, Launch-Control
